name: PR Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v2.4.0
        with:
          distribution: adopt-openj9
          java-version: '11'
          cache: gradle

      - name: Extract Secrets
        env:
          SECRET_PROPS: ${{ secrets.SECRET_PROPERTIES }}
        run: echo "$SECRET_PROPS" >> secret.properties

      - name: Build Android book
        run: ./gradlew :examples:demo:assembleDebug --stacktrace

      - name: Build desktop book
        run: ./gradlew :examples:demo:desktopJar --stacktrace

      - name: Build web book
        run: ./gradlew :examples:demo:jsJar --stacktrace
