# ---
# Github action workflow for releasing the current version of the library
# ---

name: Release Pipeline
run-name: Releasing ${{ github.ref }} to Maven Central
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Validate version
        run: ./scripts/validate_version.rb ${{ github.ref_name }}

      - name: set up JDK 11
        uses: actions/setup-java@v2.4.0
        with:
          distribution: adopt-openj9
          java-version: '11'
          cache: gradle

      - name: Extract Secrets
        env:
          SECRET_PROPS: ${{ secrets.SECRET_PROPERTIES }}
        run: echo "$SECRET_PROPS" >> secret.properties

      - name: Publish all artifacts
        env:
          OSSRH_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          SIGNING_KEY: ${{ secrets.GPG_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        run: ./gradlew publishAllPublicationsToSonatypeRepository --stacktrace

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            **/build/libs
            **/build/outputs
