name: Trunk Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v2.4.0
        with:
          distribution: adopt-openj9
          java-version: '11'
          cache: gradle

      - name: Extract Secrets
        env:
          SECRET_PROPS: ${{ secrets.SECRET_PROPERTIES }}
        run: echo "$SECRET_PROPS" >> secret.properties

      - name: Build Web Distribution
        run: ./gradlew :examples:demo:jsBrowserDistribution --stacktrace

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: 'examples/demo/build/distributions'
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
